name: Run R script weekly

on:
  schedule:
    - cron: '0 12 * * 3'  # Every Wednesday at 8 AM EST (12:00 UTC)
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up R package cache
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.R', '**/*.Rproj', '**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev

      - name: Install R packages (CRAN + your forked ffanalytics)
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        run: |
          install.packages(c(
            "dplyr", "tidyverse", "googlesheets4", "remotes",
            "httr", "httr2", "rvest", "curl"
          ), repos = "https://cloud.r-project.org")

          remotes::install_github("Borgjohn715/ffanalytics", upgrade = "never", verbose = TRUE)

          if (!requireNamespace("ffanalytics", quietly = TRUE)) {
            stop("ffanalytics package failed to install.")
          }
        shell: Rscript {0}

      - name: Decode service account JSON
        run: echo "$GCP_SHEET_CREDENTIALS" > service-account.json

      - name: Run R script
        run: Rscript update_sheet.R