name: Run ESPN ADP Update

on:
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev

      - name: Install R packages
        run: |
          install.packages(c("remotes", "googlesheets4", "dplyr", "tidyverse"))
          remotes::install_url("https://github.com/FantasyFootballAnalytics/ffanalytics/archive/refs/heads/master.zip", upgrade = "never")
        shell: Rscript {0}

      - name: Create service account file
        env:
          GCP_SHEET_CREDENTIALS: ${{ secrets.GCP_SHEET_CREDENTIALS }}
        run: |
          echo "$GCP_SHEET_CREDENTIALS" > service-account.json

      - name: Run R script
        run: |
          Rscript update_sheet.R
