name: Run R script weekly

on:
  schedule:
    - cron: '0 12 * * 3'  # Every Wednesday at 8 AM EST (12:00 UTC)
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev

      - name: Install and load R packages
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        run: |
          install.packages(c(
            "dplyr", "tidyverse", "googlesheets4", "remotes",
            "httr", "httr2", "rvest", "curl"
          ), repos = "https://cloud.r-project.org")

          cat(">>> Installing ffanalytics from GitHub...\n")
          remotes::install_github("Borgjohn715/ffanalytics", upgrade = "never", verbose = TRUE)

          cat(">>> Checking if all packages load properly...\n")
          pkgs <- c("dplyr", "tidyverse", "googlesheets4", "ffanalytics")
          for (pkg in pkgs) {
            if (!requireNamespace(pkg, quietly = TRUE)) {
              stop(paste(pkg, "failed to install"))
            } else {
              cat(">>>", pkg, "loaded successfully!\n")
            }
          }
        shell: Rscript {0}

      - name: Decode service account JSON
        run: echo "$GCP_SHEET_CREDENTIALS" > service-account.json

      - name: Run R script
        run: Rscript update_sheet.R
