name: Run R script weekly

on:
  schedule:
    - cron: '0 12 * * 3'  # Every Wednesday at 8 AM EST
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          install.packages("remotes", repos = "https://cloud.r-project.org")
          remotes::install_cran(c("dplyr", "tidyverse", "googlesheets4"))
          remotes::install_github("FantasyFootballAnalytics/ffanalytics")
        shell: Rscript {0}

      - name: Decode service account JSON
        run: echo "$GCP_SHEET_CREDENTIALS" > service-account.json

      - name: Run the R script
        run: Rscript update_sheet.R
